language: cpp

matrix:
  include:
    - os: linux
    - os: windows

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
        ./build.bat
    ;else
        mkdir -p build && cd build;
        pwd; 
    fi
