language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
    - os: windows

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./build.bat; fi

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        mkdir -p build && cd build;
        cmake .. && make;
    fi

install:
    - source set-env-vars.sh

deploy:
    provider:     releases
    skip_cleanup: true
    file: $DEPLOY_FILE
