language: cpp

matrix:
  include:
    - os: linux
    - os: windows
      env:
        - MATRIX_EVAL='choco install visualstudio2019community visualstudio2019-workload-nativedesktop && VS160COMNTOOLS="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools"'

before_install:
  - eval "${MATRIX_EVAL}" || true

before_script:
  - echo "$VS160COMNTOOLS"

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; 
    then cd ; 
    else pwd ;
    fi
  - cd "$TRAVIS_BUILD_DIR"
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; 
    then dir ; 
    else ls ;
    fi
