language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
    - os: windows

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./build.bat; fi

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        mkdir -p build && cd build;
        cmake .. && make;
    fi
